### ISSUE TITLE
*cannot find module* when using `require.resolve`

### ISSUE THREAD

**Issue by TomasHubelbauer** [yeoman/environment#116]
I am following [Integrating with Yeoman](https://yeoman.io/authoring/integrating-yeoman.html) and I have the same code, just with VS Code instead of NPM generator:

```js
const yeoman = require('yeoman-environment');

const environment = yeoman.createEnv();

// https://code.visualstudio.com/api/get-started/your-first-extension
environment.register(require.resolve('generator-code'));
environment.run();
```

I have installed both `yeoman-environment` and `generator-code` and both is in my package.json's `dependencies`.

Have I missed a step? I am getting this error:

```
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'generator-code'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\keytar-vscode-extension\code\index.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

**Comment by TomasHubelbauer** [comment]
Oh I know why now. This is because `generator-code` lacks `main`/`files` in `package.json` but `generator-npm` has it. This is a shortcoming with the VS Code generator then.
