### ISSUE TITLE
Tests failing on OS X

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/environment#26]
```
[19:36:14] Using gulpfile ~/dev/environment/gulpfile.js
[19:36:14] Starting 'static'...
[19:36:14] Starting 'test'...
Skipping tests for global generators. Please setup `NODE_PATH` environment variable to run it.


  TerminalAdapter
    #prompt()
      ✓ pass its arguments to inquirer 
    #diff()
[19:36:15] Finished 'static' after 1.1 s

removed added

letvar

      ✓ returns properly colored diffs 
    #log()
      ✓ calls console.error and perform strings interpolation 
      ✓ substitutes strings correctly when context argument is falsey 
      ✓ boolean values 
      ✓ #write() numbers 
      ✓ #write() objects 
    #log
      ✓ #write() pass strings as they are 
      ✓ #write() accepts utile#format style arguments 
dummy
      ✓ #writeln() adds a \n at the end 
✔ dummy
      ✓ #ok() adds a green "✔ " at the beginning and \n at the end 
✖ dummy
      ✓ #error() adds a green "✗ " at the beginning and \n at the end 
      statuses
        - #skip()
        - #force()
        - #create()
        - #invoke()
        - #conflict()
        - #identical()
        - #info()

  Environment
    ✓ is an instance of EventEmitter 
    constructor
      ✓ take arguments option 
      ✓ take arguments parameter option as string 
      ✓ take options parameter 
      ✓ instantiates a TerminalAdapter if none provided 
      ✓ uses the provided object as adapter if any 
      ✓ instantiates a mem-fs instance 
    #help()
      ✓ output the general help 
      ✓ output the help with a custom bin name 
    #create()
      ✓ instantiate a generator 
      ✓ instantiate a scoped generator 
      ✓ pass options.arguments 
      ✓ pass options.arguments as string 
      ✓ pass options.args (as `arguments` alias) 
      ✓ prefer options.arguments over options.args 
      ✓ default arguments to `env.arguments` 
      ✓ pass options.options 
      ✓ default options to `env.options` content 
      ✓ throws if Generator is not registered 
      ✓ add the env as property on the options 
      ✓ add the Generator resolved path on the options 
      ✓ adds the namespace on the options 
      ✓ adds the namespace as called on the options 
    #run()
      ✓ runs a registered generator 
      ✓ pass args and options to the runned generator 
      ✓ without options, it default to env.options 
      ✓ without args, it default to env.arguments 
      ✓ can take string as args 
      ✓ can take no arguments 
      ✓ launch error if generator is not found 
      ✓ returns the generator 
    #register()
      ✓ store registered generators 
      ✓ determine registered Generator namespace and resolved path 
      ✓ throw when String is not passed as first parameter 
    #registerStub()
      ✓ register a function under a namespace 
      ✓ extend simple function with Base 
[19:36:15] Plumber found unhandled error:
 Error in plugin 'gulp-mocha'
Message:
    You must provide a stub function to register.
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
Stack:
Error: You must provide a stub function to register.
    at Environment.registerStub (/Users/sindresorhus/dev/environment/lib/environment.js:9:6430)
    at Function._throws (assert.js:292:5)
    at Function.assert.throws (assert.js:318:11)
    at Context.<anonymous> (/Users/sindresorhus/dev/environment/test/environment.js:302:14)
    at callFn (/Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:250:21)
    at Test.Runnable.run (/Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:243:7)
    at Runner.runTest (/Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:373:10)
    at /Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:451:12
    at next (/Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:298:14)
    at /Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:308:7
      ✓ throws if invalid generator 
[19:36:16] Plumber found unhandled error:
 Error in plugin 'gulp-mocha'
Message:
    You must provide a namespace to register.
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
Stack:
Error: You must provide a namespace to register.
    at Environment.registerStub (/Users/sindresorhus/dev/environment/lib/environment.js:9:6704)
    at Function._throws (assert.js:292:5)
    at Function.assert.throws (assert.js:318:11)
    at Context.<anonymous> (/Users/sindresorhus/dev/environment/test/environment.js:306:14)
    at callFn (/Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:250:21)
    at Test.Runnable.run (/Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:243:7)
    at Runner.runTest (/Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:373:10)
    at /Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:451:12
    at next (/Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:298:14)
    at /Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:308:7
      ✓ throws if invalid namespace 
    #namespaces()
      ✓ get the list of namespaces 
    #getGeneratorsMeta()
      ✓ get the registered Generators metadatas 
    #namespace()
      ✓ create namespace from path 
      ✓ create namespace from scoped path 
      ✓ handle relative paths 
      ✓ handles weird paths 
      ✓ works with Windows' paths 
      ✓ remove lookups from namespace 
      ✓ remove path before the generator name 
    #get()
      ✓ get a specific generator 
      ✓ walks recursively the namespace to get the closest match 
      ✓ returns undefined if namespace is not found 
    #error()
      ✓ delegate error handling to the listener 
      ✓ throws error if no listener is set 
      ✓ returns the error 
    #alias()
      ✓ apply regex and replace with alternative value 
      ✓ apply multiple regex 
      ✓ apply latest aliases first 
      ✓ alias empty namespace to `:app` by default 
    .enforceUpdate()
      ✓ add an adapter 
      ✓ add a runLoop 
      ✓ add a shared mem-fs instance 
    .createEnv()
      ✓ create an environment 

  Environment Resolver
    #lookup()
      ✓ register local generators (194ms)
      ✓ register generators in scoped packages 
      ✓ register non-dependency local generator (586ms)
      ✓ local generators prioritized over global 
      - register global generators
      ✓ register symlinked generators 
      when there's ancestor node_modules/ folder
        ✓ register generators in ancestor node_modules directory 
        ✓ local generators are prioritized over ancestor 
    #getNpmPaths()
      with NODE_PATH
        ✓ walk up the CWD lookups dir 
        ✓ append NODE_PATH 
      without NODE_PATH
        ✓ walk up the CWD lookups dir 
        ✓ append best bet if NODE_PATH is unset 
        ✓ append default NPM dir depending on your OS 

  Store
    #add() / #get()
      ✓ normalize Generators 
      storing as module
        ✓ store and return the module 
        ✓ assign meta data to the module 
        ✓ assign dummy resolved value (can't determine the path of an instantiated) 
      storing as module path
        ✓ store and returns the required module 
        ✓ assign meta data to the module 
    #namespaces()
      ✓ return stored module namespaces 

  util
    ✓ is exposed on the Environment object 
    .duplicateEnv()
      ✓ copy environment 


  94 passing (1m)
  8 pending

---------------------|-----------|-----------|-----------|-----------|
File                 |   % Stmts |% Branches |   % Funcs |   % Lines |
---------------------|-----------|-----------|-----------|-----------|
   lib/              |     96.18 |     82.41 |        98 |     96.18 |
      adapter.js     |     95.65 |        75 |     83.33 |     95.65 |
      environment.js |     95.71 |     82.05 |       100 |     95.71 |
      resolver.js    |     95.16 |        80 |       100 |     95.16 |
      store.js       |       100 |       100 |       100 |       100 |
   lib/util/         |     77.61 |     56.25 |        60 |     77.61 |
      log.js         |        75 |     56.25 |     57.14 |        75 |
      util.js        |       100 |       100 |       100 |       100 |
---------------------|-----------|-----------|-----------|-----------|
All files            |      92.4 |     79.03 |     89.23 |      92.4 |
---------------------|-----------|-----------|-----------|-----------|


=============================== Coverage summary ===============================
Statements   : 92.4% ( 304/329 )
Branches     : 79.03% ( 98/124 )
Functions    : 89.23% ( 58/65 )
Lines        : 92.4% ( 304/329 )
================================================================================
[19:37:23] Finished 'test' after 1.13 min
[19:37:23] Starting 'coveralls'...
[19:37:23] Finished 'coveralls' after 2.96 ms
[19:37:23] Starting 'default'...
[19:37:23] Finished 'default' after 4.69 μs
```

**Comment by SBoudrias** [comment]
Well, mocha reports test as passing. The trace seems to be catched errors that are passed on the gulp-plumber error domain..?

**Comment by sindresorhus** [comment]
> The trace seems to be catched errors that are passed on the gulp-plumber error domain..?

Fixed in: https://github.com/yeoman/environment/commit/124f0f153c4e7c346947875fa0db40d946d06382

```
[03:33:09] Using gulpfile ~/dev/environment/gulpfile.js
[03:33:09] Starting 'static'...
[03:33:09] Starting 'test'...
Skipping tests for global generators. Please setup `NODE_PATH` environment variable to run it.


  TerminalAdapter
    #prompt()
      ✓ pass its arguments to inquirer 
[03:33:10] Finished 'static' after 1.53 s
    #diff()

removed added

letvar

      ✓ returns properly colored diffs 
    #log()
      ✓ calls console.error and perform strings interpolation 
      ✓ substitutes strings correctly when context argument is falsey 
      ✓ boolean values 
      ✓ #write() numbers 
      ✓ #write() objects 
    #log
      ✓ #write() pass strings as they are 
      ✓ #write() accepts utile#format style arguments 
dummy
      ✓ #writeln() adds a \n at the end 
✔ dummy
      ✓ #ok() adds a green "✔ " at the beginning and \n at the end 
✖ dummy
      ✓ #error() adds a green "✗ " at the beginning and \n at the end 
      statuses
        - #skip()
        - #force()
        - #create()
        - #invoke()
        - #conflict()
        - #identical()
        - #info()

  Environment
    ✓ is an instance of EventEmitter 
    constructor
      ✓ take arguments option 
      ✓ take arguments parameter option as string 
      ✓ take options parameter 
      ✓ instantiates a TerminalAdapter if none provided 
      ✓ uses the provided object as adapter if any 
      ✓ instantiates a mem-fs instance 
    #help()
      ✓ output the general help 
      ✓ output the help with a custom bin name 
    #create()
      ✓ instantiate a generator 
      ✓ instantiate a scoped generator 
      ✓ pass options.arguments 
      ✓ pass options.arguments as string 
      ✓ pass options.args (as `arguments` alias) 
      ✓ prefer options.arguments over options.args 
      ✓ default arguments to `env.arguments` 
      ✓ pass options.options 
      ✓ default options to `env.options` content 
      ✓ throws if Generator is not registered 
      ✓ add the env as property on the options 
      ✓ add the Generator resolved path on the options 
      ✓ adds the namespace on the options 
      ✓ adds the namespace as called on the options 
    #run()
      ✓ runs a registered generator 
      ✓ pass args and options to the runned generator 
      ✓ without options, it default to env.options 
      ✓ without args, it default to env.arguments 
      ✓ can take string as args 
      ✓ can take no arguments 
      ✓ launch error if generator is not found 
      ✓ returns the generator 
    #register()
      ✓ store registered generators 
      ✓ determine registered Generator namespace and resolved path 
      ✓ throw when String is not passed as first parameter 
    #registerStub()
      ✓ register a function under a namespace 
      ✓ extend simple function with Base 
      ✓ throws if invalid generator 
      ✓ throws if invalid namespace 
    #namespaces()
      ✓ get the list of namespaces 
    #getGeneratorsMeta()
      ✓ get the registered Generators metadatas 
    #namespace()
      ✓ create namespace from path 
      ✓ create namespace from scoped path 
      ✓ handle relative paths 
      ✓ handles weird paths 
      ✓ works with Windows' paths 
      ✓ remove lookups from namespace 
      ✓ remove path before the generator name 
    #get()
      ✓ get a specific generator 
      ✓ walks recursively the namespace to get the closest match 
      ✓ returns undefined if namespace is not found 
    #error()
      ✓ delegate error handling to the listener 
      ✓ throws error if no listener is set 
      ✓ returns the error 
    #alias()
      ✓ apply regex and replace with alternative value 
      ✓ apply multiple regex 
      ✓ apply latest aliases first 
      ✓ alias empty namespace to `:app` by default 
    .enforceUpdate()
      ✓ add an adapter 
      ✓ add a runLoop 
      ✓ add a shared mem-fs instance 
    .createEnv()
      ✓ create an environment 

  Environment Resolver
    #lookup()
      ✓ register local generators (242ms)
      ✓ register generators in scoped packages 
      ✓ register non-dependency local generator (621ms)
      ✓ local generators prioritized over global 
      - register global generators
      ✓ register symlinked generators 
      when there's ancestor node_modules/ folder
        ✓ register generators in ancestor node_modules directory 
        ✓ local generators are prioritized over ancestor 
    #getNpmPaths()
      with NODE_PATH
        ✓ walk up the CWD lookups dir 
        ✓ append NODE_PATH 
      without NODE_PATH
        ✓ walk up the CWD lookups dir 
        ✓ append best bet if NODE_PATH is unset 
        ✓ append default NPM dir depending on your OS 

  Store
    #add() / #get()
      ✓ normalize Generators 
      storing as module
        ✓ store and return the module 
        ✓ assign meta data to the module 
        ✓ assign dummy resolved value (can't determine the path of an instantiated) 
      storing as module path
        ✓ store and returns the required module 
        ✓ assign meta data to the module 
    #namespaces()
      ✓ return stored module namespaces 

  util
    ✓ is exposed on the Environment object 
    .duplicateEnv()
      ✓ copy environment 


  94 passing (52s)
  8 pending

---------------------|-----------|-----------|-----------|-----------|
File                 |   % Stmts |% Branches |   % Funcs |   % Lines |
---------------------|-----------|-----------|-----------|-----------|
   lib/              |     96.14 |     82.41 |        98 |     96.14 |
      adapter.js     |     95.65 |        75 |     83.33 |     95.65 |
      environment.js |     95.71 |     82.05 |       100 |     95.71 |
      resolver.js    |     94.92 |        80 |       100 |     94.92 |
      store.js       |       100 |       100 |       100 |       100 |
   lib/util/         |     77.61 |     56.25 |        60 |     77.61 |
      log.js         |        75 |     56.25 |     57.14 |        75 |
      util.js        |       100 |       100 |       100 |       100 |
---------------------|-----------|-----------|-----------|-----------|
All files            |     92.33 |     79.03 |     89.23 |     92.33 |
---------------------|-----------|-----------|-----------|-----------|


=============================== Coverage summary ===============================
Statements   : 92.33% ( 301/326 )
Branches     : 79.03% ( 98/124 )
Functions    : 89.23% ( 58/65 )
Lines        : 92.33% ( 301/326 )
================================================================================
[03:34:02] 'test' errored after 53 s
[03:34:02] Error in plugin 'gulp-mocha'
Message:
    You must provide a namespace to register.
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
Stack:
Error: You must provide a namespace to register.
    at Environment.registerStub (/Users/sindresorhus/dev/environment/lib/environment.js:9:6704)
    at Function._throws (assert.js:292:5)
    at Function.assert.throws (assert.js:318:11)
    at Context.<anonymous> (/Users/sindresorhus/dev/environment/test/environment.js:306:14)
    at callFn (/Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:250:21)
    at Test.Runnable.run (/Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:243:7)
    at Runner.runTest (/Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:373:10)
    at /Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:451:12
    at next (/Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:298:14)
    at /Users/sindresorhus/dev/environment/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:308:7
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by sindresorhus** [comment]
It now fails on Travis too: https://travis-ci.org/yeoman/environment/builds/47371663

**Comment by SBoudrias** [comment]
Oh god... How comes gulp changed how they handle errors on minor patches?

**Comment by sindresorhus** [comment]
It didn't. You did. You introduced `gulp-plumber` which silences stream errors https://github.com/yeoman/environment/commit/82458919a847893e812c6b0467ddd5f05a236b0a#diff-b9e12334e9eafd8341a6107dd98510c9R35 Now we have to handle them for anything to happen, which is for the better.

**Comment by SBoudrias** [comment]
I guess I'm confused as we had test suite failure since using gulp-plumber

**Comment by SBoudrias** [comment]
@sindresorhus Just checked this bug and mocha is correct to not report any error. Our tests are good.

The thing is the gulp-plumber reports error that are thrown as part of assertions (when you `assert.throws()`)

This is the test who's throwing an error: https://github.com/yeoman/environment/blob/master/test/environment.js#L305 Mocha doesn't report this as a failure, but gulp-plumber triggers an error event when the assertion run.

Not sure what the correct fix is, and the issue we have here would also impact yeoman-generator own tests.

**Comment by sindresorhus** [comment]
So why doesn't the other `assert.throws` cause a failure too? Weird.

**Comment by SBoudrias** [comment]
I think we're mostly sure this issue comes from gulp-mocha. We'll wait for a fix over there and check the status of the environment test suite afterward.

For the time being we disabled our gulp build and run our test suite with make.

**Comment by arthurvr** [comment]
> For the time being we disabled our gulp build and run our test suite with make.

Maybe we should revert that now? Seems like fixed in gulp-mocha or am I wrong? Reverted it and everything seems to pass locally.

**Comment by SBoudrias** [comment]
Checked gulp-mocha and no relevant update out of upgrading to mocha 2.0. Could that have fixed the bug? @sindresorhus

**Comment by sindresorhus** [comment]
@SBoudrias I don't know. Just keep it as is for now. I'm working on a rewrite of `gulp-mocha` that will fix all the problems. Maybe a couple of weeks off as I'm currently traveling.

**Comment by SBoudrias** [comment]
No worry, I'm fine with our current setup anyway as it'll serve as a base example for the next generator-node. It's great we can dog food it for now.

**Comment by twixie** [comment]
I have always been able to run everything correctly on both ubuntu and on Mac.
