### ISSUE TITLE
generators folder renamed to `lib/generators` in Node version 17

### ISSUE THREAD

**Issue by MarcMcIntosh** [yeoman/environment#329]
when using node version 17 it looks like the folder structure for generators is expected to be `lib/generators`

```
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/generator-foo-bar/lib/generators'
    at Object.readdirSync (node:fs:1390:3)
    at exports.readdir (/Users/marc/.nvm/versions/node/v17.0.1/lib/node_modules/prismic-cli/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:18:20)
    at Object.safeCall [as safe] (/Users/marc/.nvm/versions/node/v17.0.1/lib/node_modules/prismic-cli/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    at DirectoryReader.readNextDirectory (/Users/marc/.nvm/versions/node/v17.0.1/lib/node_modules/prismic-cli/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:78:10)
    at Readable.DirectoryReader.stream._read (/Users/marc/.nvm/versions/node/v17.0.1/lib/node_modules/prismic-cli/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:57:18)
    at Readable.read (node:internal/streams/readable:496:27)
    at readdirSync (/Users/marc/.nvm/versions/node/v17.0.1/lib/node_modules/prismic-cli/node_modules/@mrmlnc/readdir-enhanced/lib/sync/index.js:27:21)
    at Function.readdirSyncStat (/Users/marc/.nvm/versions/node/v17.0.1/lib/node_modules/prismic-cli/node_modules/@mrmlnc/readdir-enhanced/lib/index.js:34:10)
    at ReaderSync.dynamicApi (/Users/marc/.nvm/versions/node/v17.0.1/lib/node_modules/prismic-cli/node_modules/yeoman-environment/node_modules/fast-glob/out/providers/reader-sync.js:64:24)
    at ReaderSync.api (/Users/marc/.nvm/versions/node/v17.0.1/lib/node_modules/prismic-cli/node_modules/yeoman-environment/node_modules/fast-glob/out/providers/reader-sync.js:56:25)
Emitted 'error' event on Readable instance at:
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/usr/local/lib/node_modules/generator-foo-bar/lib/generators'
}

Node.js v17.0.1```

**Comment by mshima** [comment]
Looks a dependency bug.

**Comment by MarcMcIntosh** [comment]
yes, so the deps need to be updated to use `lib/generators`?

**Comment by mshima** [comment]
You may try uninstall/install to update transitive dependencies.
