### ISSUE TITLE
dependency missing on fresh yo install

### ISSUE THREAD

**Issue by themauveavenger** [yeoman/environment#68]
probably related to #67, I'm trying to do a fresh install of yo and when running it get the following error: 

```
Error: Cannot find module 'yeoman-environment'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/Cellar/nvm/0.25.4/versions/node/v4.4.7/lib/node_modules/yo/lib/router.js:9:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

I looked in the node_modules folder and yeoman-environment is missing on the new install. manually installing 1.6.1 resolves the above error. 

Node.js version: 4.4.7
npm version: 3.10.3

**Comment by SBoudrias** [comment]
Fix, try reinstalling. We hit a npm bug while publishing.
